/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--bg)',
        surface: 'var(--surface)',
        surfaceHover: 'var(--surface-hover)',
        border: 'var(--surface-border)',
        borderHover: 'var(--surface-border-hover)',
        primary: 'var(--primary)',
        primaryHover: 'var(--primary-hover)',
        primaryPressed: 'var(--primary-pressed)',
        primarySoft: 'var(--primary-soft)',
        primaryText: 'var(--primary-text)',
        textPrimary: 'var(--text)',
        textSecondary: 'var(--text-secondary)',
        textMuted: 'var(--text-muted)',
        textInverse: 'var(--text-inverse)',
        accent: 'var(--primary)',
        accentHover: 'var(--primary-hover)',
        success: 'var(--success)',
        successSoft: 'var(--success-soft)',
        warning: 'var(--warning)',
        warningSoft: 'var(--warning-soft)',
        error: 'var(--error)',
        errorSoft: 'var(--error-soft)',
        glassBg: 'var(--glass-bg)',
        glassBorder: 'var(--glass-border)',
        glassBgHover: 'var(--glass-bg-hover)',
        glassBorderHover: 'var(--glass-border-hover)',
        glassShadow: 'var(--glass-shadow)',
        glassShadowHover: 'var(--glass-shadow-hover)',
        glassBlur: 'var(--glass-blur)',
        glassBlurHover: 'var(--glass-blur-hover)',
        // Glass Depth Levels
        glassL1Bg: 'var(--glass-l1-bg)',
        glassL1Border: 'var(--glass-l1-border)',
        glassL1Shadow: 'var(--glass-l1-shadow)',
        glassL1Blur: 'var(--glass-l1-blur)',
        glassL2Bg: 'var(--glass-l2-bg)',
        glassL2Border: 'var(--glass-l2-border)',
        glassL2Shadow: 'var(--glass-l2-shadow)',
        glassL2Blur: 'var(--glass-l2-blur)',
        glassL3Bg: 'var(--glass-l3-bg)',
        glassL3Border: 'var(--glass-l3-border)',
        glassL3Shadow: 'var(--glass-l3-shadow)',
        glassL3Blur: 'var(--glass-l3-blur)',
        glassL4Bg: 'var(--glass-l4-bg)',
        glassL4Border: 'var(--glass-l4-border)',
        glassL4Shadow: 'var(--glass-l4-shadow)',
        glassL4Blur: 'var(--glass-l4-blur)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['var(--font-mono)', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1.5' }],
        'sm': ['0.875rem', { lineHeight: '1.5' }],
        'base': ['1rem', { lineHeight: '1.6' }],
        'lg': ['1.125rem', { lineHeight: '1.6' }],
        'xl': ['1.25rem', { lineHeight: '1.5' }],
        '2xl': ['1.5rem', { lineHeight: '1.4' }],
        '3xl': ['1.875rem', { lineHeight: '1.3' }],
      },
      spacing: {
        '0': '0',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
      },
      borderRadius: {
        'none': '0',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        'glass': 'var(--glass-shadow)',
        'glass-hover': 'var(--glass-shadow-hover)',
        'glass-l1': 'var(--glass-l1-shadow)',
        'glass-l2': 'var(--glass-l2-shadow)',
        'glass-l3': 'var(--glass-l3-shadow)',
        'glass-l4': 'var(--glass-l4-shadow)',
      },
      backdropBlur: {
        'xs': '2px',
        'sm': '4px',
        'md': '8px',
        'lg': '16px',
        'xl': '24px',
        '2xl': '40px',
        '3xl': '64px',
        'glass-l1': 'var(--glass-l1-blur)',
        'glass-l2': 'var(--glass-l2-blur)',
        'glass-l3': 'var(--glass-l3-blur)',
        'glass-l4': 'var(--glass-l4-blur)',
      },
      animation: {
        'fade-in': 'fadeIn var(--transition-normal)',
        'slide-in': 'slideIn var(--transition-normal)',
        'slide-up': 'slideUp var(--transition-normal)',
        'scale-in': 'scaleIn var(--transition-fast)',
        'pulse-soft': 'pulseSoft 2000ms ease-in-out infinite',
        'spin-slow': 'spin 3s linear infinite',
        'spring-in': 'springIn var(--transition-spring)',
        'spring-out': 'springOut var(--transition-fast)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { transform: 'translateX(-10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        springIn: {
          '0%': { transform: 'scale(0.92) translateY(8px)', opacity: '0' },
          '100%': { transform: 'scale(1) translateY(0)', opacity: '1' },
        },
        springOut: {
          '0%': { transform: 'scale(1) translateY(0)', opacity: '1' },
          '100%': { transform: 'scale(0.92) translateY(-8px)', opacity: '0' },
        },
      },
      transitionDuration: {
        '0': '0ms',
        '75': '75ms',
        '100': 'var(--transition-fast)',
        '150': 'var(--transition-normal)',
        '200': 'var(--transition-slow)',
        '300': '250ms',
        '500': '500ms',
        '700': '700ms',
        '1000': '1000ms',
        'spring': 'var(--transition-spring)',
      },
      transitionTimingFunction: {
        'ease-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'spring-sharp': 'cubic-bezier(0.4, 1.8, 0.2, 1)',
      },
    },
  },
  plugins: [],
}